language: node_js

node_js:
  -"8"

branches:
  only:
    - master

before_install:
  - npm install -g @angular/cli
  - npm install -g firebase-tools

script:
  - ng build --prod --aot
  cls

after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive